### ISSUE TITLE
Paid credits

### ISSUE THREAD

**Issue by Asterart** [NeverBounce/NeverBounceApi-Ruby#15]
I'm not sure when these changes were pushed to the API but last week I received an error while trying to get information about `paid_credits_remaining` from `account_info/credits_info`. So it looks like it is deleted but how now I can check the balance of the credits to do the email verification? My client was getting from my side information that he is running out of credits (both free and paid) when there were under the given limit but now I'm not able to do this. Do those changes mean that from now we are paying per check after check without a need to have a positive credit balance?

**Comment by mmollick** [comment]
Hey @Asterart, no changes were made to the API in the last week that would have changed the output of this endpoint. If the `paid_credits_remaining` key is no longer present it could be that the account's billing was changes to metered billing. Could you reach out to `support@neverbounce.com` referencing this ticket and including the email that the account is under?
