### ISSUE TITLE
Neverbounce.rb should be renamed to NeverBounce.rb

### ISSUE THREAD

**Issue by chamnap** [NeverBounce/NeverBounceApi-Ruby#2]

**Comment by mmollick** [comment]
You're right it should be renamed, is this currently causing an issue for you when trying to call the class?

**Comment by chamnap** [comment]
Yeah, it works okay on my laptop, but on the production it doesn't work. I'm not sure why. However, I rename it, it works perfectly fine.

**Comment by mmollick** [comment]
Thanks for the update! Yea that sounds about right, most ootb linux distros have case sensitive file systems, while consumer machines (OSX & Windows) are not. I'll put this on my agenda for today and get an minor release out this afternoon.

**Comment by mmollick** [comment]
Pushed a minor version bump (0.1.5) with the corrected filename!
